# CMake generated Testfile for 
# Source directory: /home/ubuntu/embeddedos/eos/tests
# Build directory: /home/ubuntu/embeddedos/eos/build_coverage/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_config "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_config")
set_tests_properties(test_config PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;5;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_graph "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_graph")
set_tests_properties(test_graph PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;10;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_hal "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_hal")
set_tests_properties(test_hal PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;15;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_kernel "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_kernel")
set_tests_properties(test_kernel PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;20;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_multicore "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_multicore")
set_tests_properties(test_multicore PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;25;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_drivers "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_drivers")
set_tests_properties(test_drivers PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;30;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_crypto "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_crypto")
set_tests_properties(test_crypto PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;35;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_security "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_security")
set_tests_properties(test_security PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;40;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_os_services "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_os_services")
set_tests_properties(test_os_services PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;45;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_ota "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_ota")
set_tests_properties(test_ota PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;50;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_sensor "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_sensor")
set_tests_properties(test_sensor PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;58;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_filesystem "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_filesystem")
set_tests_properties(test_filesystem PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;63;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_service "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_service")
set_tests_properties(test_service PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;68;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_debug "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_debug")
set_tests_properties(test_debug PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;76;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_ui_gesture "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_ui_gesture")
set_tests_properties(test_ui_gesture PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;91;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_power "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_power")
set_tests_properties(test_power PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;96;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_net "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_net")
set_tests_properties(test_net PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;101;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_motor_ctrl "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_motor_ctrl")
set_tests_properties(test_motor_ctrl PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;112;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
add_test(test_package "/home/ubuntu/embeddedos/eos/build_coverage/tests/test_package")
set_tests_properties(test_package PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;121;add_test;/home/ubuntu/embeddedos/eos/tests/CMakeLists.txt;0;")
