// SPDX-License-Identifier: MIT
// Copyright (c) 2026 EoS Project
// ISO/IEC 25000 | ISO/IEC/IEEE 15288:2023

#include "eos/lockfile.h"
#include "eos/cache.h"
#include "eos/log.h"
#include <stdio.h>
#include <string.h>
#include <ctype.h>

EosResult eos_lockfile_generate(EosLockfile *lock, const EosConfig *cfg) {
    memset(lock, 0, sizeof(*lock));
    strncpy(lock->project_name, cfg->project.name, EOS_MAX_NAME - 1);
    strncpy(lock->project_version, cfg->project.version, EOS_MAX_NAME - 1);

    for (int i = 0; i < cfg->package_count && i < EOS_MAX_PACKAGES; i++) {
        const EosPackageConfig *pc = &cfg->packages[i];
        EosLockEntry *entry = &lock->entries[lock->count];

        strncpy(entry->name, pc->name, EOS_MAX_NAME - 1);
        strncpy(entry->version, pc->version, EOS_MAX_NAME - 1);
        strncpy(entry->resolved_version, pc->version, EOS_MAX_NAME - 1);
        strncpy(entry->source, pc->source, EOS_MAX_URL - 1);
        strncpy(entry->hash, pc->hash, EOS_HASH_LEN - 1);
        entry->build_type = pc->build_type;

        /* If no hash provided, compute one from metadata */
        if (!entry->hash[0]) {
            char input[2048];
            snprintf(input, sizeof(input), "%s:%s:%s:%s",
                     entry->name, entry->version,
                     entry->source, eos_build_type_str(entry->build_type));
            eos_cache_compute_hash(input, strlen(input), entry->hash, EOS_HASH_LEN);
        }

        lock->count++;
    }

    EOS_INFO("Generated lockfile: %d entries", lock->count);
    return EOS_OK;
}

EosResult eos_lockfile_save(const EosLockfile *lock, const char *path) {
    FILE *fp = fopen(path, "w");
    if (!fp) {
        EOS_ERROR("Cannot write lockfile: %s", path);
        return EOS_ERR_IO;
    }

    fprintf(fp, "# EoS lockfile — DO NOT EDIT MANUALLY\n");
    fprintf(fp, "# Generated by eos for reproducible builds\n\n");
    fprintf(fp, "project: %s\n", lock->project_name);
    fprintf(fp, "version: %s\n", lock->project_version);
    fprintf(fp, "lock_version: 1\n\n");

    fprintf(fp, "packages:\n");
    for (int i = 0; i < lock->count; i++) {
        const EosLockEntry *e = &lock->entries[i];
        fprintf(fp, "  - name: %s\n", e->name);
        fprintf(fp, "    version: %s\n", e->version);
        fprintf(fp, "    resolved: %s\n", e->resolved_version);
        fprintf(fp, "    build: %s\n", eos_build_type_str(e->build_type));
        if (e->source[0])
            fprintf(fp, "    source: %s\n", e->source);
        if (e->hash[0])
            fprintf(fp, "    hash: %s\n", e->hash);
    }

    fclose(fp);
    EOS_INFO("Lockfile saved: %s (%d entries)", path, lock->count);
    return EOS_OK;
}

static char *lf_trim(char *s) {
    while (*s && isspace((unsigned char)*s)) s++;
    char *end = s + strlen(s) - 1;
    while (end > s && isspace((unsigned char)*end)) *end-- = '\0';
    return s;
}

EosResult eos_lockfile_load(EosLockfile *lock, const char *path) {
    FILE *fp = fopen(path, "r");
    if (!fp) return EOS_ERR_NOT_FOUND;

    memset(lock, 0, sizeof(*lock));
    char line[1024];
    int in_packages = 0;
    int entry_idx = -1;

    while (fgets(line, sizeof(line), fp)) {
        char *nl = strchr(line, '\n');
        if (nl) *nl = '\0';
        nl = strchr(line, '\r');
        if (nl) *nl = '\0';

        char *t = lf_trim(line);
        if (t[0] == '\0' || t[0] == '#') continue;

        char *colon = strchr(t, ':');
        if (!colon) continue;

        *colon = '\0';
        char *key = lf_trim(t);
        char *val = lf_trim(colon + 1);

        if (!in_packages) {
            if (strcmp(key, "project") == 0) strncpy(lock->project_name, val, EOS_MAX_NAME - 1);
            else if (strcmp(key, "version") == 0) strncpy(lock->project_version, val, EOS_MAX_NAME - 1);
            else if (strcmp(key, "packages") == 0) in_packages = 1;
            continue;
        }

        /* Inside packages section */
        if (key[0] == '-') {
            key = lf_trim(key + 1);
            if (strcmp(key, "name") == 0 && lock->count < EOS_MAX_PACKAGES) {
                entry_idx = lock->count++;
                strncpy(lock->entries[entry_idx].name, val, EOS_MAX_NAME - 1);
            }
            continue;
        }

        if (entry_idx >= 0) {
            EosLockEntry *e = &lock->entries[entry_idx];
            if (strcmp(key, "version") == 0)  strncpy(e->version, val, EOS_MAX_NAME - 1);
            else if (strcmp(key, "resolved") == 0) strncpy(e->resolved_version, val, EOS_MAX_NAME - 1);
            else if (strcmp(key, "build") == 0)    e->build_type = eos_build_type_from_str(val);
            else if (strcmp(key, "source") == 0)   strncpy(e->source, val, EOS_MAX_URL - 1);
            else if (strcmp(key, "hash") == 0)     strncpy(e->hash, val, EOS_HASH_LEN - 1);
        }
    }

    fclose(fp);
    EOS_INFO("Lockfile loaded: %s (%d entries)", path, lock->count);
    return EOS_OK;
}

int eos_lockfile_is_current(const EosLockfile *lock, const EosConfig *cfg) {
    if (strcmp(lock->project_name, cfg->project.name) != 0) return 0;
    if (lock->count != cfg->package_count) return 0;

    for (int i = 0; i < cfg->package_count; i++) {
        int found = 0;
        for (int j = 0; j < lock->count; j++) {
            if (strcmp(cfg->packages[i].name, lock->entries[j].name) == 0 &&
                strcmp(cfg->packages[i].version, lock->entries[j].version) == 0) {
                found = 1;
                break;
            }
        }
        if (!found) return 0;
    }
    return 1;
}

void eos_lockfile_dump(const EosLockfile *lock) {
    printf("Lockfile: %s v%s (%d packages)\n",
           lock->project_name, lock->project_version, lock->count);
    for (int i = 0; i < lock->count; i++) {
        const EosLockEntry *e = &lock->entries[i];
        printf("  %s %s [%s] hash=%s\n",
               e->name, e->resolved_version,
               eos_build_type_str(e->build_type),
               e->hash[0] ? e->hash : "(none)");
    }
}
