# CMake generated Testfile for 
# Source directory: /Users/kartikey/Desktop/task/eos/tests
# Build directory: /Users/kartikey/Desktop/task/eos/bsan2/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_board_configs "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_board_configs" "boards")
set_tests_properties(test_board_configs PROPERTIES  WORKING_DIRECTORY "/Users/kartikey/Desktop/task/eos" _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;23;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_os_adapter "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_os_adapter")
set_tests_properties(test_os_adapter PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;31;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_config "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_config")
set_tests_properties(test_config PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;36;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_graph "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_graph")
set_tests_properties(test_graph PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;41;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_hal "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_hal")
set_tests_properties(test_hal PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;46;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_kernel "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_kernel")
set_tests_properties(test_kernel PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;51;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_priority_inherit "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_priority_inherit")
set_tests_properties(test_priority_inherit PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;56;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_heap "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_heap")
set_tests_properties(test_heap PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;61;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_multicore "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_multicore")
set_tests_properties(test_multicore PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;66;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_drivers "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_drivers")
set_tests_properties(test_drivers PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;71;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_crypto "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_crypto")
set_tests_properties(test_crypto PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;76;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_crypto_aes "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_crypto_aes")
set_tests_properties(test_crypto_aes PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;81;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_crypto_ecc "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_crypto_ecc")
set_tests_properties(test_crypto_ecc PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;85;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_crypto_rsa "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_crypto_rsa")
set_tests_properties(test_crypto_rsa PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;89;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_crypto_sha512 "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_crypto_sha512")
set_tests_properties(test_crypto_sha512 PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;93;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_security "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_security")
set_tests_properties(test_security PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;98;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_os_services "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_os_services")
set_tests_properties(test_os_services PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;103;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_ota "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_ota")
set_tests_properties(test_ota PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;108;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_sensor "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_sensor")
set_tests_properties(test_sensor PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;116;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_filesystem "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_filesystem")
set_tests_properties(test_filesystem PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;121;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_service "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_service")
set_tests_properties(test_service PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;126;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_debug "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_debug")
set_tests_properties(test_debug PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;134;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_ui_gesture "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_ui_gesture")
set_tests_properties(test_ui_gesture PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;149;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_power "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_power")
set_tests_properties(test_power PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;154;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_net "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_net")
set_tests_properties(test_net PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;166;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_motor_ctrl "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_motor_ctrl")
set_tests_properties(test_motor_ctrl PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;177;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_package "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_package")
set_tests_properties(test_package PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;186;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_devicetree "/Users/kartikey/Desktop/task/eos/bsan2/tests/test_devicetree")
set_tests_properties(test_devicetree PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;191;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
subdirs("fuzz")
