# CMake generated Testfile for 
# Source directory: /Users/kartikey/Desktop/task/eos/tests
# Build directory: /Users/kartikey/Desktop/task/eos/bsan/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_board_configs "/Users/kartikey/Desktop/task/eos/bsan/tests/test_board_configs" "boards")
set_tests_properties(test_board_configs PROPERTIES  WORKING_DIRECTORY "/Users/kartikey/Desktop/task/eos" _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;4;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_os_adapter "/Users/kartikey/Desktop/task/eos/bsan/tests/test_os_adapter")
set_tests_properties(test_os_adapter PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;12;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_config "/Users/kartikey/Desktop/task/eos/bsan/tests/test_config")
set_tests_properties(test_config PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;17;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_graph "/Users/kartikey/Desktop/task/eos/bsan/tests/test_graph")
set_tests_properties(test_graph PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;22;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_hal "/Users/kartikey/Desktop/task/eos/bsan/tests/test_hal")
set_tests_properties(test_hal PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;27;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_kernel "/Users/kartikey/Desktop/task/eos/bsan/tests/test_kernel")
set_tests_properties(test_kernel PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;32;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_priority_inherit "/Users/kartikey/Desktop/task/eos/bsan/tests/test_priority_inherit")
set_tests_properties(test_priority_inherit PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;37;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_heap "/Users/kartikey/Desktop/task/eos/bsan/tests/test_heap")
set_tests_properties(test_heap PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;42;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_multicore "/Users/kartikey/Desktop/task/eos/bsan/tests/test_multicore")
set_tests_properties(test_multicore PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;47;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_drivers "/Users/kartikey/Desktop/task/eos/bsan/tests/test_drivers")
set_tests_properties(test_drivers PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;52;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_crypto "/Users/kartikey/Desktop/task/eos/bsan/tests/test_crypto")
set_tests_properties(test_crypto PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;57;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_crypto_aes "/Users/kartikey/Desktop/task/eos/bsan/tests/test_crypto_aes")
set_tests_properties(test_crypto_aes PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;62;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_crypto_ecc "/Users/kartikey/Desktop/task/eos/bsan/tests/test_crypto_ecc")
set_tests_properties(test_crypto_ecc PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;66;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_crypto_rsa "/Users/kartikey/Desktop/task/eos/bsan/tests/test_crypto_rsa")
set_tests_properties(test_crypto_rsa PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;70;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_crypto_sha512 "/Users/kartikey/Desktop/task/eos/bsan/tests/test_crypto_sha512")
set_tests_properties(test_crypto_sha512 PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;74;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_security "/Users/kartikey/Desktop/task/eos/bsan/tests/test_security")
set_tests_properties(test_security PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;79;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_os_services "/Users/kartikey/Desktop/task/eos/bsan/tests/test_os_services")
set_tests_properties(test_os_services PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;84;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_ota "/Users/kartikey/Desktop/task/eos/bsan/tests/test_ota")
set_tests_properties(test_ota PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;89;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_sensor "/Users/kartikey/Desktop/task/eos/bsan/tests/test_sensor")
set_tests_properties(test_sensor PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;97;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_filesystem "/Users/kartikey/Desktop/task/eos/bsan/tests/test_filesystem")
set_tests_properties(test_filesystem PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;102;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_service "/Users/kartikey/Desktop/task/eos/bsan/tests/test_service")
set_tests_properties(test_service PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;107;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_debug "/Users/kartikey/Desktop/task/eos/bsan/tests/test_debug")
set_tests_properties(test_debug PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;115;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_ui_gesture "/Users/kartikey/Desktop/task/eos/bsan/tests/test_ui_gesture")
set_tests_properties(test_ui_gesture PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;130;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_power "/Users/kartikey/Desktop/task/eos/bsan/tests/test_power")
set_tests_properties(test_power PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;135;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_net "/Users/kartikey/Desktop/task/eos/bsan/tests/test_net")
set_tests_properties(test_net PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;147;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_motor_ctrl "/Users/kartikey/Desktop/task/eos/bsan/tests/test_motor_ctrl")
set_tests_properties(test_motor_ctrl PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;158;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_package "/Users/kartikey/Desktop/task/eos/bsan/tests/test_package")
set_tests_properties(test_package PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;167;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
add_test(test_devicetree "/Users/kartikey/Desktop/task/eos/bsan/tests/test_devicetree")
set_tests_properties(test_devicetree PROPERTIES  _BACKTRACE_TRIPLES "/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;172;add_test;/Users/kartikey/Desktop/task/eos/tests/CMakeLists.txt;0;")
subdirs("fuzz")
